### ISSUE TITLE
fitcnv not found

### ISSUE THREAD

**Issue by ilyco** [qenvio/dryhic#10]
I've been running through your usage example and I ran into the following issue:
```
info$cn <- fitcnv(info$tot_oned)[[2]]
Error in fitcnv(info$tot_oned) : could not find function "fitcnv"
```

**Comment by qenvio** [comment]
Thanks for reporting!

It was an issue with the Fortran code export. @gui11aume pointed to the solution and it is fixed. It should run fine now.

Please let me know if it works fine for you.

:)

**Comment by qenvio** [comment]
Commit b0b35efc5ac264a4df60d917ca389ee5df82ad9f fix the issue
