### ISSUE TITLE
bias_hg38

### ISSUE THREAD

**Issue by ilyco** [qenvio/dryhic#11]
Could you please provide more details about how you computed 
```
data(bias_hg38)
data(enzymes_hg38)
```

or how can this be adapted to hg19?

**Comment by qenvio** [comment]
Tutorial incoming ...

**Comment by qenvio** [comment]
You can find a script to compute the biases [here](https://github.com/qenvio/dryhic/blob/master/inst/src/prepare_bias_from_scratch.r).

Results using this bias `data.frame` compared to the ones in the `dryhicdata` package might differ slightly.

**Comment by ilyco** [comment]
Thank you very much!
